# ============================================================
# AUTO-GENERATED VIEWS — DO NOT EDIT
# Generated by structurizr-mkdocs-generatr
# Re-run the CLI to regenerate. Hand-written views in other
# files take priority (matching keys are skipped).
# ============================================================

# --- System Landscape Views ---



# [auto-generated] All software systems (no actors)
systemlandscape "SystemLandscapeSoftwareSystems" {
    description "System Landscape - Software Systems"
    include internetBankingSystem mainframe email atm
    autoLayout
}

# [auto-generated] Big Bank plc group landscape
systemlandscape "SystemLandscapeBigBankplc" {
    description "System Landscape - Big Bank plc"
    include internetBankingSystem mainframe email atm backoffice customer supportStaff
    autoLayout
}

# [auto-generated] Personal Banking Customer landscape
systemlandscape "SystemLandscapeUserPersonalBankingCustomer" {
    description "System Landscape - Personal Banking Customer"
    include customer atm email internetBankingSystem
    autoLayout
}

# [auto-generated] Customer Service Staff landscape
systemlandscape "SystemLandscapeUserCustomerServiceStaff" {
    description "System Landscape - Customer Service Staff"
    include supportStaff mainframe
    autoLayout
}

# [auto-generated] Back Office Staff landscape
systemlandscape "SystemLandscapeUserBackOfficeStaff" {
    description "System Landscape - Back Office Staff"
    include backoffice mainframe
    autoLayout
}

# [auto-generated] All actors (no systems)
systemlandscape "SystemLandscapeUsers" {
    description "System Landscape - Actors"
    include customer supportStaff backoffice
    autoLayout
}


# --- System Context Views ---


# Big Bank plc
# [auto-generated]
systemContext internetBankingSystem "SystemContextInternetBankingSystem" {
    description "System Context - Internet Banking System"
    include *
    autoLayout
}

# [auto-generated]
systemContext mainframe "SystemContextMainframe" {
    description "System Context - Mainframe Banking System"
    include *
    autoLayout
}

# [auto-generated]
systemContext email "SystemContextEmail" {
    description "System Context - E-mail System"
    include *
    autoLayout
}

# [auto-generated]
systemContext atm "SystemContextAtm" {
    description "System Context - ATM"
    include *
    autoLayout
}


# --- Container Views ---


# Big Bank plc
# [auto-generated]
container internetBankingSystem "ContainerInternetBankingSystem" {
    description "Container - Internet Banking System"
    include *
    autoLayout
}


# --- Deployment Views ---


# [auto-generated]
deployment mainframe "Development" "DeploymentEnvdevelopmentMainframe" {
    description "Deployment - Development - Mainframe Banking System"
    include *
    autoLayout
}

# [auto-generated]
deployment mainframe "Live" "DeploymentEnvliveMainframe" {
    description "Deployment - Live - Mainframe Banking System"
    include *
    autoLayout
}

# [auto-generated]
deployment email "Environment Landscape" "DeploymentEnvenvironmentlandscapeEmail" {
    description "Deployment - Environment Landscape - E-mail System"
    include *
    autoLayout
}

# [auto-generated]
deployment mainframe "Environment Landscape" "DeploymentEnvenvironmentlandscapeMainframe" {
    description "Deployment - Environment Landscape - Mainframe Banking System"
    include *
    autoLayout
}

