# ============================================================
# AUTO-GENERATED VIEWS — DO NOT EDIT
# Generated by structurizr-mkdocs-generatr
# Re-run the CLI to regenerate. Hand-written views in other
# files take priority (matching keys are skipped).
# ============================================================

# --- System Landscape Views ---


# [auto-generated] Full system landscape
systemlandscape "SystemLandscape" {
    description "System Landscape"
    include *
    autoLayout
}

# [auto-generated] All software systems (no users)
systemlandscape "SystemLandscapeSoftwareSystems" {
    description "System Landscape - Software Systems"
    include softwareSystemSalesforceCrm softwareSystemStripe softwareSystemTicketingPlatform softwareSystemWebStore softwareSystemSponsorshipPortal softwareSystemFanEngagement softwareSystemProductDevelopment softwareSystemMarketingPlatform softwareSystemClubWebsite softwareSystemSapS4Hana softwareSystemHrPortal softwareSystemComplianceManager softwareSystemStrategyPortal softwareSystemExternalRelations softwareSystemMicrosoftEntraId softwareSystemDatabricks softwareSystemAzureAiFoundry softwareSystemIntegrationPlatform softwareSystemDataPlatform softwareSystemStadiumManagement softwareSystemCashlessPayment softwareSystemLogisticsPlanner softwareSystemMatchdayOperations softwareSystemPlayerPerformance softwareSystemMedicalRecords softwareSystemYouthAcademy
    autoLayout
}

# [auto-generated] Commercial group landscape
systemlandscape "SystemLandscapeCommercial" {
    description "System Landscape - Commercial"
    include softwareSystemSalesforceCrm softwareSystemStripe softwareSystemTicketingPlatform softwareSystemWebStore softwareSystemSponsorshipPortal softwareSystemFanEngagement softwareSystemProductDevelopment softwareSystemMarketingPlatform softwareSystemClubWebsite userCommunicationsManager userFan userMarketingManager userMerchandisingManager userProductManager userPublic userSeasonTicketHolder userSponsor userTicketingAgent
    autoLayout
}

# [auto-generated] Corporate group landscape
systemlandscape "SystemLandscapeCorporate" {
    description "System Landscape - Corporate"
    include softwareSystemSapS4Hana softwareSystemHrPortal softwareSystemComplianceManager softwareSystemStrategyPortal softwareSystemExternalRelations userCommunicationsManager userComplianceOfficer userFinanceController userHrManager userMerchandisingManager userStrategyDirector
    autoLayout
}

# [auto-generated] IT group landscape
systemlandscape "SystemLandscapeIT" {
    description "System Landscape - IT"
    include softwareSystemMicrosoftEntraId softwareSystemDatabricks softwareSystemAzureAiFoundry softwareSystemIntegrationPlatform softwareSystemDataPlatform userDataAnalyst userFinanceController userItArchitect
    autoLayout
}

# [auto-generated] Operations group landscape
systemlandscape "SystemLandscapeOperations" {
    description "System Landscape - Operations"
    include softwareSystemStadiumManagement softwareSystemCashlessPayment softwareSystemLogisticsPlanner softwareSystemMatchdayOperations userFan userMatchdayDirector userMerchandisingManager userStadiumOperator
    autoLayout
}

# [auto-generated] Sporting group landscape
systemlandscape "SystemLandscapeSporting" {
    description "System Landscape - Sporting"
    include softwareSystemPlayerPerformance softwareSystemMedicalRecords softwareSystemYouthAcademy userHeadCoach userMedicalStaff userYouthScout
    autoLayout
}

# [auto-generated] Fan landscape
systemlandscape "SystemLandscapeUserFan" {
    description "System Landscape - Fan"
    include userFan softwareSystemCashlessPayment softwareSystemClubWebsite softwareSystemFanEngagement softwareSystemTicketingPlatform softwareSystemWebStore
    autoLayout
}

# [auto-generated] Season Ticket Holder landscape
systemlandscape "SystemLandscapeUserSeasonTicketHolder" {
    description "System Landscape - Season Ticket Holder"
    include userSeasonTicketHolder softwareSystemFanEngagement softwareSystemTicketingPlatform
    autoLayout
}

# [auto-generated] Public landscape
systemlandscape "SystemLandscapeUserPublic" {
    description "System Landscape - Public"
    include userPublic softwareSystemClubWebsite softwareSystemWebStore
    autoLayout
}

# [auto-generated] Sponsor landscape
systemlandscape "SystemLandscapeUserSponsor" {
    description "System Landscape - Sponsor"
    include userSponsor softwareSystemSponsorshipPortal
    autoLayout
}

# [auto-generated] Ticketing Agent landscape
systemlandscape "SystemLandscapeUserTicketingAgent" {
    description "System Landscape - Ticketing Agent"
    include userTicketingAgent softwareSystemSalesforceCrm softwareSystemTicketingPlatform
    autoLayout
}

# [auto-generated] Merchandising Manager landscape
systemlandscape "SystemLandscapeUserMerchandisingManager" {
    description "System Landscape - Merchandising Manager"
    include userMerchandisingManager softwareSystemLogisticsPlanner softwareSystemSapS4Hana softwareSystemWebStore
    autoLayout
}

# [auto-generated] Stadium Operator landscape
systemlandscape "SystemLandscapeUserStadiumOperator" {
    description "System Landscape - Stadium Operator"
    include userStadiumOperator softwareSystemCashlessPayment softwareSystemMatchdayOperations softwareSystemStadiumManagement
    autoLayout
}

# [auto-generated] Head Coach landscape
systemlandscape "SystemLandscapeUserHeadCoach" {
    description "System Landscape - Head Coach"
    include userHeadCoach softwareSystemMedicalRecords softwareSystemPlayerPerformance softwareSystemYouthAcademy
    autoLayout
}

# [auto-generated] Medical Staff landscape
systemlandscape "SystemLandscapeUserMedicalStaff" {
    description "System Landscape - Medical Staff"
    include userMedicalStaff softwareSystemMedicalRecords
    autoLayout
}

# [auto-generated] Youth Scout landscape
systemlandscape "SystemLandscapeUserYouthScout" {
    description "System Landscape - Youth Scout"
    include userYouthScout softwareSystemYouthAcademy
    autoLayout
}

# [auto-generated] HR Manager landscape
systemlandscape "SystemLandscapeUserHRManager" {
    description "System Landscape - HR Manager"
    include userHrManager softwareSystemHrPortal softwareSystemSapS4Hana
    autoLayout
}

# [auto-generated] Finance Controller landscape
systemlandscape "SystemLandscapeUserFinanceController" {
    description "System Landscape - Finance Controller"
    include userFinanceController softwareSystemComplianceManager softwareSystemDataPlatform softwareSystemSapS4Hana softwareSystemStrategyPortal
    autoLayout
}

# [auto-generated] Data Analyst landscape
systemlandscape "SystemLandscapeUserDataAnalyst" {
    description "System Landscape - Data Analyst"
    include userDataAnalyst softwareSystemAzureAiFoundry softwareSystemDataPlatform softwareSystemDatabricks
    autoLayout
}

# [auto-generated] IT Architect landscape
systemlandscape "SystemLandscapeUserITArchitect" {
    description "System Landscape - IT Architect"
    include userItArchitect softwareSystemIntegrationPlatform
    autoLayout
}

# [auto-generated] Compliance Officer landscape
systemlandscape "SystemLandscapeUserComplianceOfficer" {
    description "System Landscape - Compliance Officer"
    include userComplianceOfficer softwareSystemComplianceManager
    autoLayout
}

# [auto-generated] Strategy Director landscape
systemlandscape "SystemLandscapeUserStrategyDirector" {
    description "System Landscape - Strategy Director"
    include userStrategyDirector softwareSystemStrategyPortal
    autoLayout
}

# [auto-generated] Product Manager landscape
systemlandscape "SystemLandscapeUserProductManager" {
    description "System Landscape - Product Manager"
    include userProductManager softwareSystemProductDevelopment
    autoLayout
}

# [auto-generated] Marketing Manager landscape
systemlandscape "SystemLandscapeUserMarketingManager" {
    description "System Landscape - Marketing Manager"
    include userMarketingManager softwareSystemMarketingPlatform
    autoLayout
}

# [auto-generated] Matchday Director landscape
systemlandscape "SystemLandscapeUserMatchdayDirector" {
    description "System Landscape - Matchday Director"
    include userMatchdayDirector softwareSystemMatchdayOperations
    autoLayout
}

# [auto-generated] Communications Manager landscape
systemlandscape "SystemLandscapeUserCommunicationsManager" {
    description "System Landscape - Communications Manager"
    include userCommunicationsManager softwareSystemClubWebsite softwareSystemExternalRelations
    autoLayout
}

# [auto-generated] All users (no systems)
systemlandscape "SystemLandscapeUsers" {
    description "System Landscape - Users"
    include userFan userSeasonTicketHolder userPublic userSponsor userTicketingAgent userMerchandisingManager userStadiumOperator userHeadCoach userMedicalStaff userYouthScout userHrManager userFinanceController userDataAnalyst userItArchitect userComplianceOfficer userStrategyDirector userProductManager userMarketingManager userMatchdayDirector userCommunicationsManager
    autoLayout
}


# --- System Context Views ---


# Commercial
# [auto-generated]
systemContext softwareSystemSalesforceCrm "SystemContextSalesforceCrm" {
    description "System Context - Salesforce CRM"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemStripe "SystemContextStripe" {
    description "System Context - Stripe"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemTicketingPlatform "SystemContextTicketingPlatform" {
    description "System Context - Ticketing Platform"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemWebStore "SystemContextWebStore" {
    description "System Context - Web Store"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemSponsorshipPortal "SystemContextSponsorshipPortal" {
    description "System Context - Sponsorship Portal"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemFanEngagement "SystemContextFanEngagement" {
    description "System Context - Fan Engagement Platform"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemProductDevelopment "SystemContextProductDevelopment" {
    description "System Context - Product Development"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemMarketingPlatform "SystemContextMarketingPlatform" {
    description "System Context - Marketing Platform"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemClubWebsite "SystemContextClubWebsite" {
    description "System Context - Club Website"
    include *
    autoLayout
}

# Corporate
# [auto-generated]
systemContext softwareSystemSapS4Hana "SystemContextSapS4Hana" {
    description "System Context - SAP S4HANA"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemHrPortal "SystemContextHrPortal" {
    description "System Context - HR Portal"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemComplianceManager "SystemContextComplianceManager" {
    description "System Context - Compliance Manager"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemStrategyPortal "SystemContextStrategyPortal" {
    description "System Context - Strategy Portal"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemExternalRelations "SystemContextExternalRelations" {
    description "System Context - External Relations Portal"
    include *
    autoLayout
}

# IT
# [auto-generated]
systemContext softwareSystemMicrosoftEntraId "SystemContextMicrosoftEntraId" {
    description "System Context - Microsoft Entra ID"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemDatabricks "SystemContextDatabricks" {
    description "System Context - Databricks"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemAzureAiFoundry "SystemContextAzureAiFoundry" {
    description "System Context - Azure AI Foundry"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemIntegrationPlatform "SystemContextIntegrationPlatform" {
    description "System Context - Integration Platform"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemDataPlatform "SystemContextDataPlatform" {
    description "System Context - Data Platform"
    include *
    autoLayout
}

# Operations
# [auto-generated]
systemContext softwareSystemStadiumManagement "SystemContextStadiumManagement" {
    description "System Context - Stadium Management"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemCashlessPayment "SystemContextCashlessPayment" {
    description "System Context - Cashless Payment"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemLogisticsPlanner "SystemContextLogisticsPlanner" {
    description "System Context - Logistics Planner"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemMatchdayOperations "SystemContextMatchdayOperations" {
    description "System Context - Matchday Operations"
    include *
    autoLayout
}

# Sporting
# [auto-generated]
systemContext softwareSystemPlayerPerformance "SystemContextPlayerPerformance" {
    description "System Context - Player Performance"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemMedicalRecords "SystemContextMedicalRecords" {
    description "System Context - Medical Records"
    include *
    autoLayout
}

# [auto-generated]
systemContext softwareSystemYouthAcademy "SystemContextYouthAcademy" {
    description "System Context - Youth Academy"
    include *
    autoLayout
}


# --- Container Views ---


# Commercial
# [auto-generated]
container softwareSystemSalesforceCrm "ContainerSalesforceCrm" {
    description "Container - Salesforce CRM"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemStripe "ContainerStripe" {
    description "Container - Stripe"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemTicketingPlatform "ContainerTicketingPlatform" {
    description "Container - Ticketing Platform"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemWebStore "ContainerWebStore" {
    description "Container - Web Store"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemSponsorshipPortal "ContainerSponsorshipPortal" {
    description "Container - Sponsorship Portal"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemFanEngagement "ContainerFanEngagement" {
    description "Container - Fan Engagement Platform"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemProductDevelopment "ContainerProductDevelopment" {
    description "Container - Product Development"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemMarketingPlatform "ContainerMarketingPlatform" {
    description "Container - Marketing Platform"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemClubWebsite "ContainerClubWebsite" {
    description "Container - Club Website"
    include *
    autoLayout
}

# Corporate
# [auto-generated]
container softwareSystemSapS4Hana "ContainerSapS4Hana" {
    description "Container - SAP S4HANA"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemHrPortal "ContainerHrPortal" {
    description "Container - HR Portal"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemComplianceManager "ContainerComplianceManager" {
    description "Container - Compliance Manager"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemStrategyPortal "ContainerStrategyPortal" {
    description "Container - Strategy Portal"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemExternalRelations "ContainerExternalRelations" {
    description "Container - External Relations Portal"
    include *
    autoLayout
}

# IT
# [auto-generated]
container softwareSystemMicrosoftEntraId "ContainerMicrosoftEntraId" {
    description "Container - Microsoft Entra ID"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemDatabricks "ContainerDatabricks" {
    description "Container - Databricks"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemAzureAiFoundry "ContainerAzureAiFoundry" {
    description "Container - Azure AI Foundry"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemIntegrationPlatform "ContainerIntegrationPlatform" {
    description "Container - Integration Platform"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemDataPlatform "ContainerDataPlatform" {
    description "Container - Data Platform"
    include *
    autoLayout
}

# Operations
# [auto-generated]
container softwareSystemStadiumManagement "ContainerStadiumManagement" {
    description "Container - Stadium Management"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemCashlessPayment "ContainerCashlessPayment" {
    description "Container - Cashless Payment"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemLogisticsPlanner "ContainerLogisticsPlanner" {
    description "Container - Logistics Planner"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemMatchdayOperations "ContainerMatchdayOperations" {
    description "Container - Matchday Operations"
    include *
    autoLayout
}

# Sporting
# [auto-generated]
container softwareSystemPlayerPerformance "ContainerPlayerPerformance" {
    description "Container - Player Performance"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemMedicalRecords "ContainerMedicalRecords" {
    description "Container - Medical Records"
    include *
    autoLayout
}

# [auto-generated]
container softwareSystemYouthAcademy "ContainerYouthAcademy" {
    description "Container - Youth Academy"
    include *
    autoLayout
}


# --- Deployment Views ---


# [auto-generated] Acceptance — Azure Cloud
deployment * deploymentAcceptance "DeploymentAcceptanceAzure" {
    description "Deployment - Acceptance - Azure Cloud"
    include deploymentNodeAcceptanceAzure
    autoLayout
}

# [auto-generated]
deployment softwareSystemAzureAiFoundry deploymentAcceptance "DeploymentAcceptanceAzureAiFoundry" {
    description "Deployment - Acceptance - Azure AI Foundry"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemCashlessPayment deploymentAcceptance "DeploymentAcceptanceCashlessPayment" {
    description "Deployment - Acceptance - Cashless Payment"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemClubWebsite deploymentAcceptance "DeploymentAcceptanceClubWebsite" {
    description "Deployment - Acceptance - Club Website"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemComplianceManager deploymentAcceptance "DeploymentAcceptanceComplianceManager" {
    description "Deployment - Acceptance - Compliance Manager"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemDataPlatform deploymentAcceptance "DeploymentAcceptanceDataPlatform" {
    description "Deployment - Acceptance - Data Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemExternalRelations deploymentAcceptance "DeploymentAcceptanceExternalRelations" {
    description "Deployment - Acceptance - External Relations Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemFanEngagement deploymentAcceptance "DeploymentAcceptanceFanEngagement" {
    description "Deployment - Acceptance - Fan Engagement Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemHrPortal deploymentAcceptance "DeploymentAcceptanceHrPortal" {
    description "Deployment - Acceptance - HR Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemIntegrationPlatform deploymentAcceptance "DeploymentAcceptanceIntegrationPlatform" {
    description "Deployment - Acceptance - Integration Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemLogisticsPlanner deploymentAcceptance "DeploymentAcceptanceLogisticsPlanner" {
    description "Deployment - Acceptance - Logistics Planner"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMarketingPlatform deploymentAcceptance "DeploymentAcceptanceMarketingPlatform" {
    description "Deployment - Acceptance - Marketing Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMatchdayOperations deploymentAcceptance "DeploymentAcceptanceMatchdayOperations" {
    description "Deployment - Acceptance - Matchday Operations"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMedicalRecords deploymentAcceptance "DeploymentAcceptanceMedicalRecords" {
    description "Deployment - Acceptance - Medical Records"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemPlayerPerformance deploymentAcceptance "DeploymentAcceptancePlayerPerformance" {
    description "Deployment - Acceptance - Player Performance"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemProductDevelopment deploymentAcceptance "DeploymentAcceptanceProductDevelopment" {
    description "Deployment - Acceptance - Product Development"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemSponsorshipPortal deploymentAcceptance "DeploymentAcceptanceSponsorshipPortal" {
    description "Deployment - Acceptance - Sponsorship Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemStadiumManagement deploymentAcceptance "DeploymentAcceptanceStadiumManagement" {
    description "Deployment - Acceptance - Stadium Management"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemStrategyPortal deploymentAcceptance "DeploymentAcceptanceStrategyPortal" {
    description "Deployment - Acceptance - Strategy Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemTicketingPlatform deploymentAcceptance "DeploymentAcceptanceTicketingPlatform" {
    description "Deployment - Acceptance - Ticketing Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemWebStore deploymentAcceptance "DeploymentAcceptanceWebStore" {
    description "Deployment - Acceptance - Web Store"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemYouthAcademy deploymentAcceptance "DeploymentAcceptanceYouthAcademy" {
    description "Deployment - Acceptance - Youth Academy"
    include *
    autoLayout
}

# [auto-generated] Development — Azure Cloud
deployment * deploymentDevelopment "DeploymentDevelopmentAzure" {
    description "Deployment - Development - Azure Cloud"
    include deploymentNodeDevelopmentAzure
    autoLayout
}

# [auto-generated]
deployment softwareSystemAzureAiFoundry deploymentDevelopment "DeploymentDevelopmentAzureAiFoundry" {
    description "Deployment - Development - Azure AI Foundry"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemCashlessPayment deploymentDevelopment "DeploymentDevelopmentCashlessPayment" {
    description "Deployment - Development - Cashless Payment"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemClubWebsite deploymentDevelopment "DeploymentDevelopmentClubWebsite" {
    description "Deployment - Development - Club Website"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemComplianceManager deploymentDevelopment "DeploymentDevelopmentComplianceManager" {
    description "Deployment - Development - Compliance Manager"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemDataPlatform deploymentDevelopment "DeploymentDevelopmentDataPlatform" {
    description "Deployment - Development - Data Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemExternalRelations deploymentDevelopment "DeploymentDevelopmentExternalRelations" {
    description "Deployment - Development - External Relations Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemFanEngagement deploymentDevelopment "DeploymentDevelopmentFanEngagement" {
    description "Deployment - Development - Fan Engagement Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemHrPortal deploymentDevelopment "DeploymentDevelopmentHrPortal" {
    description "Deployment - Development - HR Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemIntegrationPlatform deploymentDevelopment "DeploymentDevelopmentIntegrationPlatform" {
    description "Deployment - Development - Integration Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemLogisticsPlanner deploymentDevelopment "DeploymentDevelopmentLogisticsPlanner" {
    description "Deployment - Development - Logistics Planner"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMarketingPlatform deploymentDevelopment "DeploymentDevelopmentMarketingPlatform" {
    description "Deployment - Development - Marketing Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMatchdayOperations deploymentDevelopment "DeploymentDevelopmentMatchdayOperations" {
    description "Deployment - Development - Matchday Operations"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMedicalRecords deploymentDevelopment "DeploymentDevelopmentMedicalRecords" {
    description "Deployment - Development - Medical Records"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemPlayerPerformance deploymentDevelopment "DeploymentDevelopmentPlayerPerformance" {
    description "Deployment - Development - Player Performance"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemProductDevelopment deploymentDevelopment "DeploymentDevelopmentProductDevelopment" {
    description "Deployment - Development - Product Development"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemSponsorshipPortal deploymentDevelopment "DeploymentDevelopmentSponsorshipPortal" {
    description "Deployment - Development - Sponsorship Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemStadiumManagement deploymentDevelopment "DeploymentDevelopmentStadiumManagement" {
    description "Deployment - Development - Stadium Management"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemStrategyPortal deploymentDevelopment "DeploymentDevelopmentStrategyPortal" {
    description "Deployment - Development - Strategy Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemTicketingPlatform deploymentDevelopment "DeploymentDevelopmentTicketingPlatform" {
    description "Deployment - Development - Ticketing Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemWebStore deploymentDevelopment "DeploymentDevelopmentWebStore" {
    description "Deployment - Development - Web Store"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemYouthAcademy deploymentDevelopment "DeploymentDevelopmentYouthAcademy" {
    description "Deployment - Development - Youth Academy"
    include *
    autoLayout
}

# [auto-generated] Production — On-Premise
deployment * deploymentProduction "DeploymentProductionOnPremise" {
    description "Deployment - Production - On-Premise"
    include deploymentNodeProductionOnPremise
    autoLayout
}

# [auto-generated] Production — Azure Cloud
deployment * deploymentProduction "DeploymentProductionAzure" {
    description "Deployment - Production - Azure Cloud"
    include deploymentNodeProductionAzure
    autoLayout
}

# [auto-generated] Production — AWS Cloud
deployment * deploymentProduction "DeploymentProductionAws" {
    description "Deployment - Production - AWS Cloud"
    include deploymentNodeProductionAws
    autoLayout
}

# [auto-generated]
deployment softwareSystemAzureAiFoundry deploymentProduction "DeploymentProductionAzureAiFoundry" {
    description "Deployment - Production - Azure AI Foundry"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemCashlessPayment deploymentProduction "DeploymentProductionCashlessPayment" {
    description "Deployment - Production - Cashless Payment"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemClubWebsite deploymentProduction "DeploymentProductionClubWebsite" {
    description "Deployment - Production - Club Website"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemComplianceManager deploymentProduction "DeploymentProductionComplianceManager" {
    description "Deployment - Production - Compliance Manager"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemDataPlatform deploymentProduction "DeploymentProductionDataPlatform" {
    description "Deployment - Production - Data Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemDatabricks deploymentProduction "DeploymentProductionDatabricks" {
    description "Deployment - Production - Databricks"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemExternalRelations deploymentProduction "DeploymentProductionExternalRelations" {
    description "Deployment - Production - External Relations Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemFanEngagement deploymentProduction "DeploymentProductionFanEngagement" {
    description "Deployment - Production - Fan Engagement Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemHrPortal deploymentProduction "DeploymentProductionHrPortal" {
    description "Deployment - Production - HR Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemIntegrationPlatform deploymentProduction "DeploymentProductionIntegrationPlatform" {
    description "Deployment - Production - Integration Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemLogisticsPlanner deploymentProduction "DeploymentProductionLogisticsPlanner" {
    description "Deployment - Production - Logistics Planner"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMarketingPlatform deploymentProduction "DeploymentProductionMarketingPlatform" {
    description "Deployment - Production - Marketing Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMatchdayOperations deploymentProduction "DeploymentProductionMatchdayOperations" {
    description "Deployment - Production - Matchday Operations"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMedicalRecords deploymentProduction "DeploymentProductionMedicalRecords" {
    description "Deployment - Production - Medical Records"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemPlayerPerformance deploymentProduction "DeploymentProductionPlayerPerformance" {
    description "Deployment - Production - Player Performance"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemProductDevelopment deploymentProduction "DeploymentProductionProductDevelopment" {
    description "Deployment - Production - Product Development"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemSalesforceCrm deploymentProduction "DeploymentProductionSalesforceCrm" {
    description "Deployment - Production - Salesforce CRM"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemSapS4Hana deploymentProduction "DeploymentProductionSapS4Hana" {
    description "Deployment - Production - SAP S4HANA"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemSponsorshipPortal deploymentProduction "DeploymentProductionSponsorshipPortal" {
    description "Deployment - Production - Sponsorship Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemStadiumManagement deploymentProduction "DeploymentProductionStadiumManagement" {
    description "Deployment - Production - Stadium Management"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemStrategyPortal deploymentProduction "DeploymentProductionStrategyPortal" {
    description "Deployment - Production - Strategy Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemStripe deploymentProduction "DeploymentProductionStripe" {
    description "Deployment - Production - Stripe"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemTicketingPlatform deploymentProduction "DeploymentProductionTicketingPlatform" {
    description "Deployment - Production - Ticketing Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemWebStore deploymentProduction "DeploymentProductionWebStore" {
    description "Deployment - Production - Web Store"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemYouthAcademy deploymentProduction "DeploymentProductionYouthAcademy" {
    description "Deployment - Production - Youth Academy"
    include *
    autoLayout
}

# [auto-generated] Test — Azure Cloud
deployment * deploymentTest "DeploymentTestAzure" {
    description "Deployment - Test - Azure Cloud"
    include deploymentNodeTestAzure
    autoLayout
}

# [auto-generated]
deployment softwareSystemAzureAiFoundry deploymentTest "DeploymentTestAzureAiFoundry" {
    description "Deployment - Test - Azure AI Foundry"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemCashlessPayment deploymentTest "DeploymentTestCashlessPayment" {
    description "Deployment - Test - Cashless Payment"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemClubWebsite deploymentTest "DeploymentTestClubWebsite" {
    description "Deployment - Test - Club Website"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemComplianceManager deploymentTest "DeploymentTestComplianceManager" {
    description "Deployment - Test - Compliance Manager"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemDataPlatform deploymentTest "DeploymentTestDataPlatform" {
    description "Deployment - Test - Data Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemExternalRelations deploymentTest "DeploymentTestExternalRelations" {
    description "Deployment - Test - External Relations Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemFanEngagement deploymentTest "DeploymentTestFanEngagement" {
    description "Deployment - Test - Fan Engagement Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemHrPortal deploymentTest "DeploymentTestHrPortal" {
    description "Deployment - Test - HR Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemIntegrationPlatform deploymentTest "DeploymentTestIntegrationPlatform" {
    description "Deployment - Test - Integration Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemLogisticsPlanner deploymentTest "DeploymentTestLogisticsPlanner" {
    description "Deployment - Test - Logistics Planner"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMarketingPlatform deploymentTest "DeploymentTestMarketingPlatform" {
    description "Deployment - Test - Marketing Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMatchdayOperations deploymentTest "DeploymentTestMatchdayOperations" {
    description "Deployment - Test - Matchday Operations"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemMedicalRecords deploymentTest "DeploymentTestMedicalRecords" {
    description "Deployment - Test - Medical Records"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemPlayerPerformance deploymentTest "DeploymentTestPlayerPerformance" {
    description "Deployment - Test - Player Performance"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemProductDevelopment deploymentTest "DeploymentTestProductDevelopment" {
    description "Deployment - Test - Product Development"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemSponsorshipPortal deploymentTest "DeploymentTestSponsorshipPortal" {
    description "Deployment - Test - Sponsorship Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemStadiumManagement deploymentTest "DeploymentTestStadiumManagement" {
    description "Deployment - Test - Stadium Management"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemStrategyPortal deploymentTest "DeploymentTestStrategyPortal" {
    description "Deployment - Test - Strategy Portal"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemTicketingPlatform deploymentTest "DeploymentTestTicketingPlatform" {
    description "Deployment - Test - Ticketing Platform"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemWebStore deploymentTest "DeploymentTestWebStore" {
    description "Deployment - Test - Web Store"
    include *
    autoLayout
}

# [auto-generated]
deployment softwareSystemYouthAcademy deploymentTest "DeploymentTestYouthAcademy" {
    description "Deployment - Test - Youth Academy"
    include *
    autoLayout
}

